def raise_exception():
    raise TypeError("An error occurred")
